version: "3"

services:

  db:
  
    image: postgres:11
    ports:
      - "5432:5432"
  web:

    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DOCKER=TRUE
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
